# config.yaml

# Select Tools
###############################################################################
METHOD: salmon           # featureCounts, htseq, salmon
ALIGNER: bt2             # none, bt2, bbmap
TRIMMER: trimmomatic     # bbduk, trimmomatic, untrimmed
ASSEMBLER: megahit       # megahit, trinity
THREADS: 8
MAX_MEMORY: 300000000000        # bytes

# Genomic alignment and quantification
###############################################################################

# Dictionary with genomes that can be aligned against.
genome:
  ncbi_url: # ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/004/765/GCF_003004765.2_ASM300476v2
  ref_file:

# Trimmer Adapter File
###############################################################################
adapter_file: utils/adapters/TruSeq3-PE-2.fa

# Annotating Assembled Transcriptome
###############################################################################
diamondDB:
  name: uniref90
  url: ftp://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz

# RNASeq Data
###############################################################################

samples: samples.tsv

sample_ids: [SRR6877528, SRR6877529, SRR6877530,
             SRR6877531, SRR6877532, SRR6877533,
             SRR6877534, SRR6877535, SRR6877536]
